#!/bin/sh

on=$(uname)
if [ $on = "Linux" ]; then
        campPID=3
        campIPCID=1
else
    if [ $on = "FreeBSD" ]; then
        campPID=7
        campIPCID=2
    else
       if [ $on = "Darwin" ]; then
           campPID=7
           campIPCID=2
       else
           echo "Error: sistema $on desconegut"
           exit 0
       fi
    fi
fi

propietari=$(whoami)
n=0

for ipctype in "-m" "-q" "-s"
do
	# obtenir tots els ipcs d'un usuari
        ipcs $ipctype -p | grep $propietari | tr -s ' ' >/tmp/ipcs+pids.txt
	# obtenir la llista de pids actius del propietari
	nactius=$(ps -u $propietari -o pid >/tmp/pids.txt)

	# per cada procés d'aquest usuari que té un ipc
    for pid in $(cut -f $campPID -d ' ' /tmp/ipcs+pids.txt | sort -n | uniq)
    do
	nactius=$(grep $pid /tmp/pids.txt | wc -l) # és un procés actiu?
        if [ $nactius -eq 0 ]; then
            num=$(grep " $pid " /tmp/ipcs+pids.txt | wc -l)
            echo "proc $pid no és actiu i té $num ipcs de tipus $ipctype pendents"
            for ipcid in $(grep " $pid " /tmp/ipcs+pids.txt | cut -f $campIPCID -d ' ')
            do
                ipcrm $ipctype $ipcid
                n=$(($n+1))
            done
        fi
    done
done

if [ $on = "Darwin" -o $on = "FreeBSD" ]; then
   num=$(cat /tmp/ipcs+pids.txt | wc -l)
   if [ $num -gt 0 ]; then echo "$propietari té $num ipcs de tipus -s pendents"; fi
   for ipcid in $(cat /tmp/ipcs+pids.txt | cut -f $campIPCID -d ' ')
   do 
      ipcrm -s $ipcid
      n=$(($n+1))
   done
fi   

rm /tmp/ipcs+pids.txt
rm /tmp/pids.txt

if [ $n -gt 0 ]; then
    echo "S'han eliminat $n ipcs pertanyents a $propietari"
else
    echo "No s'ha trobat cap ipc que pertanyi a un procés ja acabat"
fi

